"""empty message

Revision ID: 861acf57e4d4
Revises: 975a23b7f13f
Create Date: 2020-12-29 19:07:46.896365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861acf57e4d4'
down_revision = '975a23b7f13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('lead', sa.String(length=240), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('watched', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
